# Generated by Django 3.0.6 on 2020-05-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('mapNum', models.IntegerField()),
                ('score', models.IntegerField()),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('startx', models.IntegerField()),
                ('starty', models.IntegerField()),
                ('endx', models.IntegerField()),
                ('endy', models.IntegerField()),
                ('treasurex', models.IntegerField()),
                ('treasurey', models.IntegerField()),
                ('characterType', models.IntegerField()),
                ('characterState', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('passMapNumber', models.IntegerField()),
            ],
        ),
    ]
