# Generated by Django 3.0.6 on 2020-06-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='userLevel',
            field=models.IntegerField(default=1),
        ),
    ]
